<?php /** @var $block \Netreviews\Avisverifies\Block\Product\ReviewRenderer */ ?>
<?php if($block->nbReviews > 0): ?>
    <div class="netreviews-stars">
        <span>
            <div class="netreviews_bg_stars_big listStars">
                <?php echo $block->ntavAddStarsByRate ?>
            </div>
            <a class="netreviews-stars-link stars-link-category-page" rel="nofollow"><span><?php echo $block->nbReviews; ?></span>&nbsp;<?php echo __('review(s)'); ?></a>
        </span>
    </div>
<?php endif; ?>
