<?php
/** @var Mirasvit\GdprCookie\Block\CookieGroupBlock $block */
?>
<?php
$group   = $block->getCookieGroup();
$groupId = $group->getId();

$disabled = $group->isRequired() ? 'disabled' : '';
$checked  = !$group->isRequired() && !$block->getOptionalGroupsChecked() ? '' : 'checked';
?>
<div class="cookie-group-container cookie-group-container-<?= $groupId; ?>">
    <div class="title-container">
        <span class="title">
            <?= $block->escapeHtml(__($group->getName())); ?>
        </span>
        <?php $inputAttrName = 'name="allowed-group-' . $groupId . '"'; ?>
        <label class="switch">
            <span style="display: none"><?= __('Allow') ?></span>
            <input id="allowed-group-<?= $groupId ?>" class="checkbox" type="checkbox" value="1" <?= $disabled; ?> <?= $checked; ?> data-group-id="<?= $groupId; ?>" <?= $inputAttrName ?> aria-label="<?= __('Allow') ?>">
            <span class="slider round <?= $disabled; ?>"></span>
        </label>

        <div class="content">
            <div>
                <?= $block->escapeHtml(__($group->getDescription())); ?>
            </div>
            <table>
                <tr>
                    <th><?= __('Name') ?></th>
                    <th><?= __('Description') ?></th>
                    <th><?= __('Lifetime') ?></th>
                </tr>
                <?php foreach ($block->getCookies() as $cookie): ?>
                    <tr>
                        <td><?= $block->escapeHtml($cookie->getName()) ?></td>
                        <td><?= $block->escapeHtml($cookie->getDescription()) ?></td>
                        <td><?= $block->humanReadableLifetime($cookie->getLifetime()) ?></td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    </div>

</div>

<script>
    require([
        'jquery',
        'collapsible'
    ], function ($) {
        var elSelector = ".cookie-group-container-<?= $groupId; ?>";
        $(elSelector).collapsible(
            {header: $(elSelector + " .title"), content: $(elSelector + " .content")}
        );
    });
</script>
