<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
	    <li class="level0 nav-1 category-item first level-top ui-menu-item">
	    	<a href="/" class="level-top ui-corner-all" role="menuitem">
		    	<span class="fa fa-home"></span>
		    	<span><?php echo __("Home"); ?></span>
	    	</a>
	    </li>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
        
	    <?php if($isLoggedIn): ?>
		    <li class="level0 nav-1 category-item first level-top ui-menu-item right">
		    	<a href="/customer/account/logout" class="level-top ui-corner-all" role="menuitem">
			    	<span class="fa fa-times-circle"></span>
		    	</a>
		    </li>
		<?php endif; ?>
	    <li class="level0 nav-1 category-item first level-top ui-menu-item right">
	    	<a href="/customer/account" class="level-top ui-corner-all" role="menuitem">
		    	<span class="fa fa-user"></span>
		    	<span><?php echo __("My Account"); ?></span>
	    	</a>
	    </li>
	    
    </ul>
</nav>
